from datetime import datetime, timezone
from pathlib import Path
from string import Template
from uuid import uuid4
import hashlib
import json
from fnmatch import fnmatchcase
from typing import Any
from orchestrator.agents.roles import ROLES

from orchestrator.config.models import AgentResult
from orchestrator.agents.history import classify_task
from orchestrator.agents.cost import TaskProfile
from orchestrator.agents.skills import SkillDispatcher
from orchestrator.validation.parser import sanitize_text
from orchestrator.workflow.protection import snapshot_protected_paths, verify_protected_paths, is_protected_path


def load_prompt(role: str, **values: Any) -> str:
    spec = ROLES[role]
    path = Path(__file__).resolve().parents[1] / "prompts" / spec.prompt_file
    template_text = path.read_text(encoding="utf-8")

    # Unified internal contract: canonical parameter is 'artifact'
    # Resolve any alias divergence: artifact, artifacts, response, context, artifact_content
    artifact: Any = values.pop("artifact", None)

    for alias in ("artifact_content", "context", "artifacts"):
        if artifact is None and alias in values:
            val = values.pop(alias)
            if val is not None:
                artifact = val
        else:
            values.pop(alias, None)

    # Do not use an empty generic 'response' field if template expects 'artifact'
    response_val = values.pop("response", None)
    if artifact is None and response_val is not None:
        if isinstance(response_val, str) and response_val.strip():
            artifact = response_val
        elif not isinstance(response_val, str) and response_val:
            artifact = response_val

    # If artifact is a Path or a path string to an existing file, read real content
    if isinstance(artifact, Path):
        artifact = artifact.read_text(encoding="utf-8")
    elif isinstance(artifact, str) and "\n" not in artifact and len(artifact) < 1024:
        try:
            p = Path(artifact)
            if p.is_file():
                artifact = p.read_text(encoding="utf-8")
        except OSError:
            pass
    elif isinstance(artifact, (dict, list)):
        artifact = json.dumps(artifact, indent=2)

    # Prompt final must not contain an empty artifact when template expects $artifact
    if "$artifact" in template_text or "${artifact}" in template_text:
        if artifact is None or (isinstance(artifact, str) and not artifact.strip()):
            raise ValueError(f"Artifact content cannot be empty for role '{role}'")
        values["artifact"] = artifact

    str_values = {k: str(v) for k, v in values.items()}
    return Template(template_text).safe_substitute(**str_values)




class AgentRunner:
    def __init__(self, providers, router, store=None, workflow_id=None, safety=None, cost_router=None, execution_policy_router=None, skill_dispatcher=None, is_canary=None):
        self.providers, self.router, self.store = providers, router, store
        self.on_fallback=None
        self.on_call=None
        self.on_call_complete=None
        self.workflow_id=workflow_id
        self.safety=safety or {}
        self.cost_router=cost_router
        self.execution_policy_router=execution_policy_router
        self.skill_dispatcher=skill_dispatcher or SkillDispatcher(providers)
        self.model_feedback=[]
        self.validation_results=[]
        self.calls=0
        self.task_calls={}
        self.active_elapsed=0.0
        self.active_stage_name=None
        self.active_stage_role=None
        self.active_stage_artifacts=[]
        if is_canary is not None:
            self.is_canary = is_canary
        elif store and workflow_id:
            wf = store.get_workflow(workflow_id)
            feat = (wf or {}).get("feature", "")
            self.is_canary = "provider-summary" in str(feat)
        else:
            self.is_canary = False
        if store and workflow_id:
            self.calls,self.task_calls=store.agent_call_counts(workflow_id)
            self.active_elapsed=store.active_execution_seconds(workflow_id)

    def set_stage_context(self, stage: str, role: str, artifacts: Any = ()):
        self.active_stage_name = stage
        self.active_stage_role = role
        self.active_stage_artifacts = list(artifacts or ())


    @staticmethod
    def _snapshot(root):
        if root is None: return {}
        base=Path(root).resolve()
        # Include untracked source files, excluding metadata, operational
        # state, build outputs and Python bytecode generated by imports.
        ignored = {".git", ".venv", ".orchestrator", "build", "dist", "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache"}
        return {p.relative_to(base).as_posix():hashlib.sha256(
            str(p.lstat().st_mode).encode() + b"\0" +
            (str(p.readlink()).encode() if p.is_symlink() else p.read_bytes())
        ).hexdigest() for p in base.rglob("*")
            if not ignored.intersection(p.relative_to(base).parts)
            and p.suffix != ".pyc" and (p.is_file() or p.is_symlink())}

    @staticmethod
    def _in_scope(path, allowed):
        parts=Path(path).parts
        for item in allowed:
            expected=Path(item.rstrip("/")).parts
            # Match globs component by component: '*' must never cross '/'.
            if len(parts)<len(expected) or (not item.endswith("/") and len(parts)!=len(expected)):
                continue
            if all(fnmatchcase(part, pattern) for part,pattern in zip(parts,expected)):
                return True
        return False

    @staticmethod
    def _scope_error(root, permitted):
        base=Path(root).resolve()
        for item in permitted:
            path=Path(item)
            if not item or path.is_absolute() or ".." in path.parts or "**" in path.parts or not path.parts:
                return f"SCOPE_VIOLATION: unsafe writable path {item!r}"
            prefix=base
            for part in path.parts:
                if any(char in part for char in "*?["):
                    break
                prefix=prefix/part
                if prefix.is_symlink():
                    return f"SCOPE_VIOLATION: writable path traverses symlink {item!r}"
        return None

    def _budget_error(self, task_id):
        if self.calls>=int(self.safety.get("max_agent_calls_per_workflow",100)): return "BUDGET_EXCEEDED: workflow agent calls"
        if task_id and self.task_calls.get(task_id,0)>=int(self.safety.get("max_agent_calls_per_task",12)): return "BUDGET_EXCEEDED: task agent calls"
        active=self.store.active_execution_seconds(self.workflow_id) if self.store and self.workflow_id else self.active_elapsed
        if active>=float(self.safety.get("max_wall_time",7200)): return "BUDGET_EXCEEDED: active execution time"
        return None

    def record_validation(self, agent_result, validation_result, stage=None, evidence=None, raw_response=None):
        role = getattr(agent_result, "role", "unknown")
        provider = getattr(agent_result, "provider", "unknown")
        model = getattr(agent_result, "model", None)
        if not stage:
            stage_map = {
                "constitution_validator": "CONSTITUTION_VALIDATE",
                "specification_validator": "SPECIFICATION_VALIDATE",
                "plan_validator": "PLAN_VALIDATE",
                "tasks_validator": "TASKS_VALIDATE",
                "test_validator": "RED_VALIDATE",
                "code_reviewer": "CODE_REVIEW",
                "final_reviewer": "FINAL_REVIEW",
            }
            stage = stage_map.get(role, role.upper())

        status = getattr(validation_result, "status", "BLOCKED")
        if status not in {"PASS", "REVISE", "BLOCKED", "PARSE_ERROR"}:
            status = "BLOCKED"

        summary = getattr(validation_result, "summary", "") or ""
        issues_raw = getattr(validation_result, "issues", []) or []
        issues: list[str] = []
        for issue in issues_raw:
            if isinstance(issue, str):
                issues.append(sanitize_text(issue))
            elif isinstance(issue, dict) and "description" in issue:
                issues.append(sanitize_text(str(issue["description"])))
            else:
                issues.append(sanitize_text(str(issue)))

        raw = raw_response or getattr(validation_result, "raw_output", "") or getattr(agent_result, "stdout", "") or ""
        sanitized_raw = sanitize_text(raw)
        timestamp = getattr(validation_result, "timestamp", "") or datetime.now(timezone.utc).isoformat()

        entry = {
            "stage": stage,
            "role": role,
            "provider": provider,
            "model": model,
            "status": status,
            "reason": sanitize_text(summary),
            "summary": sanitize_text(summary),
            "issues": issues,
            "evidence": evidence or {},
            "raw_response": sanitized_raw,
            "timestamp": timestamp,
        }


        self.validation_results.append(entry)
        if self.store and self.workflow_id:
            self.store.record_validation(self.workflow_id, entry)

        malformed = status == "PARSE_ERROR" or summary in ("Could not parse strict validation output", "Malformed issue schema")
        if malformed:
            self.record_model_feedback(agent_result, "STRUCTURED_OUTPUT_FAILURE", summary)
        if not self.store: return
        execution_id = agent_result.usage.get("execution_id") if hasattr(agent_result, "usage") and isinstance(agent_result.usage, dict) else None
        if execution_id:
            self.store.update_execution_outcome(execution_id, structured_output_valid=not malformed, validator_accepted=status == "PASS", blocked=status in {"BLOCKED", "PARSE_ERROR"})
        if malformed:
            self.store.record_metric(provider, model, role, "structured_output_failure")
        elif status != "PASS":
            self.store.record_metric(provider, model, role, "validator_rejection")

    def record_model_feedback(self, agent_result, category, reason=""):
        """Only attributable failures can unlock the next cost escalation level."""
        event={"provider":agent_result.provider,"model":agent_result.model,"category":category,"reason":reason,
               "role":agent_result.role,"task_id":agent_result.usage.get("task_id")}
        self.model_feedback.append(event)
        if self.store and agent_result.usage.get("execution_id"):
            self.store.update_execution_outcome(agent_result.usage["execution_id"],model_failure_category=category,model_failure_reason=reason)

    def run_skill(self, role, provider, model, skill_name, arguments, cwd, execution_policy=None,
                  timeout=None, fallback=True, task=None, task_id=None, allowed_paths=None,
                  expected_outputs=None, exclude_providers=None, artifacts=None, attempt=1, **kwargs):
        """Run a skill through the normal router, safety, retry, and telemetry path."""
        return self.run(role, arguments, cwd=cwd, timeout=timeout, override_provider=provider,
                        override_model=model, fallback=fallback, task=task, task_id=task_id,
                        allowed_paths=allowed_paths, expected_outputs=expected_outputs,
                        skill_name=skill_name, execution_policy=execution_policy,
                        exclude_providers=exclude_providers, artifacts=artifacts, attempt=attempt, **kwargs)

    def run(self, role: str, prompt: str, cwd=None, timeout=None, override_provider=None, override_model=None, fallback=True, exclude_providers=None, author_provider=None, task=None, task_id=None, allowed_paths=None, expected_outputs=None, skill_name=None, execution_policy=None, artifacts=None, attempt=1, author_model=None, author_models=None, author_role=None, numeric_sensitive: bool = False):
        artifacts_list = list(artifacts or ())
        if (
            self.active_stage_role == role
            and self.active_stage_artifacts
            and not artifacts_list
        ):
            raise RuntimeError(
                f"INVARIANCE_VIOLATION: stage '{self.active_stage_name}' declared artifacts_supplied "
                f"{self.active_stage_artifacts}, but agent call for role '{role}' received empty artifacts."
            )
        invocation_id=str(uuid4())
        route_excludes=set(exclude_providers or ())
        if author_provider is None and exclude_providers and len(exclude_providers)==1:
            author_provider=next(iter(exclude_providers))
            route_excludes.discard(author_provider)
        task_id=task_id or (task or {}).get("id")
        kind,difficulty=classify_task(role,task)
        profile=TaskProfile.derive(role,task)
        if author_models:
            auth_models_list = list(author_models)
            if author_model and not any(author_model == (item[0] if isinstance(item, tuple) else item) for item in auth_models_list):
                auth_models_list.append((author_model, author_role or ""))
        elif author_model:
            auth_models_list = [(author_model, author_role or "")]
        else:
            auth_models_list = []
        is_numeric = numeric_sensitive or bool((task or {}).get("numeric_sensitive", False))
        route = self.router.route(
            role, override_provider=override_provider, override_model=override_model,
            exclude=route_excludes, author_provider=author_provider, task=task,
            author_models=auth_models_list, author_role=author_role, numeric_sensitive=is_numeric
        )
        decision=None
        if self.cost_router and route.provider!="unavailable":
            failures=(self.store.model_failure_events(self.workflow_id,task_id,role) if self.store and self.workflow_id else self.model_feedback)
            decision=self.cost_router.assess(role,route,task,author_provider,failures,override_model,(task or {}).get("astra_escalation_reason"))
            route=decision["actual_route"]
        if route.provider == "unavailable":
            if "INSUFFICIENT_INDEPENDENT_PROVIDERS" in getattr(route, "reason", ""):
                return AgentResult("unavailable", None, role, False, error="INSUFFICIENT_INDEPENDENT_PROVIDERS")
            return AgentResult("unavailable", None, role, False, error="PROVIDER_FAILURE: no provider available")
        def cost_safety_error(chosen, assessment):
            if not assessment: return None
            row=next((item for item in assessment["candidates"] if item["provider"]==chosen.provider and item["model"]==chosen.model),None)
            if row and row["level"]=="ASTRA" and not assessment["astra_escalation_reason"]:
                return "ASTRA_ESCALATION_REQUIRED: explicit escalation reason is missing"
            if row and any("budget exhausted" in reason for reason in row["eligibility_reasons"]):
                return "BUDGET_EXCEEDED: strong model call limit"
            if row and row["level"]=="OPUS" and "extraordinary_fallback_requires_override" in row["eligibility_reasons"]:
                return "OPUS_OVERRIDE_REQUIRED: extraordinary model is outside the normal ladder"
            return None
        route_error=cost_safety_error(route,decision)
        if route_error: return AgentResult(route.provider,route.model,role,False,error=route_error)
        configured_scope=self.safety.get("file_scopes",{}).get(role)
        permitted=([] if ROLES[role].validation else list(allowed_paths if allowed_paths is not None else
            (configured_scope if isinstance(configured_scope,list) else
             (["tests/","fixtures/","conftest.py","pytest.ini","tox.ini"] if role=="test_designer" else []))))
        enforce_scope=bool(self.safety.get("safety_mode")=="strict" or allowed_paths is not None or
                           skill_name or ROLES[role].validation)
        if enforce_scope and ROLES[role].edits_files and not permitted:
            return AgentResult(route.provider,route.model,role,False,
                               error="SCOPE_VIOLATION: writable paths are not declared for this role")
        if enforce_scope and cwd is None:
            if ROLES[role].edits_files:
                return AgentResult(route.provider,route.model,role,False,
                                   error="SCOPE_VIOLATION: workspace is required for scope enforcement")
            # Read-only calls without a workspace have no filesystem to snapshot.
            enforce_scope=False
        scope_error=self._scope_error(cwd,permitted) if enforce_scope else None
        if scope_error:
            return AgentResult(route.provider,route.model,role,False,error=scope_error)
        def execute(chosen,attempt):
            budget=self._budget_error(task_id)
            if budget: return AgentResult(chosen.provider,chosen.model,role,False,error=budget)
            outputs=expected_outputs or (["structured validation JSON"] if ROLES[role].validation else (["task tests"] if role=="test_designer" else (["declared production files"] if role in {"coder","refactorer"} else ["SDD artifact or structured task output"])))
            if self.on_call:
                try:
                    on_call_ok = self.on_call(role,chosen.provider,chosen.model,task_id,permitted,outputs,artifacts=artifacts_list,attempt=attempt)
                except TypeError:
                    try:
                        on_call_ok = self.on_call(role,chosen.provider,chosen.model,task_id,permitted,outputs,artifacts=artifacts_list)
                    except TypeError:
                        on_call_ok = self.on_call(role,chosen.provider,chosen.model,task_id,permitted,outputs)
                if not on_call_ok:
                    return AgentResult(chosen.provider,chosen.model,role,False,error="INTERACTIVE_ABORT")

            self.calls+=1
            if task_id: self.task_calls[task_id]=self.task_calls.get(task_id,0)+1
            if self.store and self.workflow_id:
                item=self.store.get_workflow(self.workflow_id)
                if item: self.store.update_workflow(self.workflow_id,"RUNNING_AGENT",{**item["state"],"running_role":role,"running_task":task_id,"running_provider":chosen.provider,"running_model":chosen.model},task_id)
            policy=execution_policy if execution_policy is not None else (self.execution_policy_router.select(role,chosen.provider,profile) if self.execution_policy_router else None)
            scoped_prompt=prompt
            if enforce_scope:
                scoped_prompt += ("\n\nPython execution contract: allowed write paths (workspace-relative) = "
                                  + json.dumps(permitted) + ". All other paths are read-only. "
                                  "Do not alter Git metadata or orchestrator state. "
                                  "An empty list permits no filesystem writes.")
                if skill_name:
                    scoped_prompt += (" Materialize required canonical artifacts only at these paths; "
                                      "stdout/response is execution metadata, never artifact content. "
                                      "This scope overrides broader file-writing steps in the installed skill.")
            effective_prompt=(policy.prefix+"\n\n"+scoped_prompt) if policy and policy.prefix else scoped_prompt
            permissions="read" if ROLES[role].validation else None
            prov = self.providers.get(chosen.provider)
            if prov and hasattr(prov, "list_models"):
                catalog = prov.list_models()
                if catalog and chosen.model and chosen.model not in catalog:
                    return AgentResult(chosen.provider, chosen.model, role, False,
                                       error=f"MODEL_CATALOG_UNAVAILABLE: model '{chosen.model}' not in {chosen.provider} catalog")
            try:
                protected_before = snapshot_protected_paths(cwd, is_canary=self.is_canary) if cwd else {}
                before = self._snapshot(cwd) if enforce_scope else {}
            except OSError as exc:
                return AgentResult(chosen.provider, chosen.model, role, False,
                                   error=f"SCOPE_VIOLATION: workspace cannot be inspected: {exc}")
            try:
                if skill_name:
                    result=self.skill_dispatcher.run_skill(role,chosen.provider,chosen.model,skill_name,scoped_prompt,cwd,policy,timeout,permissions)
                    effective_prompt=f"skill:{skill_name}\n{effective_prompt}"
                else:
                    result=self.providers[chosen.provider].run(effective_prompt,role,chosen.model,cwd,timeout,permissions)
            except Exception as exc:
                result=AgentResult(chosen.provider,chosen.model,role,False,
                                   error=f"PROVIDER_FAILURE: {type(exc).__name__}: {exc}")
            if cwd:
                protected_violations = verify_protected_paths(cwd, protected_before, is_canary=self.is_canary)
                if protected_violations:
                    result.success = False
                    result.error = "PROTECTED_PATH_VIOLATION: " + ", ".join(protected_violations)
                    result.usage["protected_path_violations"] = protected_violations
                    return result
            if enforce_scope:
                try:
                    after=self._snapshot(cwd)
                except OSError as exc:
                    result.success=False
                    result.error=f"SCOPE_VIOLATION: workspace cannot be inspected: {exc}"
                    return result
                changed=sorted(path for path in set(before)|set(after) if before.get(path)!=after.get(path))
                violations=[path for path in changed if not self._in_scope(path,permitted) or is_protected_path(path, is_canary=self.is_canary)]
                if violations:
                    result.success=False; result.error="SCOPE_VIOLATION: "+", ".join(violations)
                    result.usage["scope_violations"]=violations
                if changed and not result.success and self.store and self.workflow_id:
                    item=self.store.get_workflow(self.workflow_id)
                    if item: self.store.update_workflow(self.workflow_id,"PARTIAL_WRITE",{**item["state"],"interrupted_stage":"PARTIAL_WRITE","partial_files":changed},task_id)
                if changed and not result.success and not violations:
                    result.error="PARTIAL_WRITE: provider failed after modifying "+", ".join(changed)
                    result.usage["partial_files"]=changed
            self.active_elapsed+=max(0.0,result.duration)
            if self.on_call_complete: self.on_call_complete(result)
            result.usage["validation_independence"]=chosen.independence
            result.usage["validation_independence_reason"]=chosen.reason if author_provider else None
            result.usage["routing_selection_mode"]=chosen.selection_mode
            result.usage["task_type"]=kind; result.usage["task_complexity"]=difficulty
            result.usage["task_id"]=task_id
            res_model = result.resolved_model or result.model or chosen.model
            if not result.resolution_source or result.resolution_source == "unavailable":
                res_src = "adapter_explicit" if (result.model or result.resolved_model) else "cli_default"
            else:
                res_src = result.resolution_source
            result.resolved_model = res_model
            result.resolution_source = res_src
            result.usage["requested_model"] = chosen.model
            result.usage["resolved_model"] = res_model
            result.usage["resolution_source"] = res_src
            result.usage["requested_effort"] = result.requested_effort
            result.usage["resolved_effort"] = result.resolved_effort
            result.usage["fallback_reason"] = getattr(result, "fallback_reason", None)
            if not hasattr(self, "stage_resolved_models"):
                self.stage_resolved_models = {}
            self.stage_resolved_models[role] = {
                "requested_model": chosen.model,
                "resolved_model": res_model,
                "resolution_source": res_src,
                "provider": chosen.provider,
            }
            if policy:
                result.usage.update({"ponytail_enabled":policy.ponytail_enabled,"caveman_enabled":policy.caveman_enabled,
                    "policy_source":policy.policy_source,"policy_overhead_estimate":policy.policy_overhead_estimate,
                    "policy_enabled_reason":policy.policy_enabled_reason})
            if decision:
                chosen_cost=next((item for item in decision["candidates"] if item["provider"]==chosen.provider and item["model"]==chosen.model),None)
                result.usage.update({"cost_aware_recommendation":decision["cost_aware_recommendation"],"cost_aware_mode":decision["mode"],
                    "escalation_level":next((item["level"] for item in decision["candidates"] if item["provider"]==chosen.provider and item["model"]==chosen.model),None),
                    "escalation_reason":decision["astra_escalation_reason"],
                    "estimated_cost":chosen_cost["expected_cost"] if chosen_cost else None})
            if self.store:
                eid=self.store.record_provider_execution(result,effective_prompt,attempt=attempt,invocation_id=invocation_id,workflow_id=self.workflow_id,task_id=task_id,task_type=kind,task_complexity=difficulty,
                    outcome={"success":result.success,"first_pass_success":result.success and attempt==1,"attempts":attempt,"blocked":bool(result.error and result.error.startswith(("BUDGET_EXCEEDED","SCOPE_VIOLATION","PARTIAL_WRITE"))),"provider_failure":bool(result.error and result.error.startswith("PROVIDER_FAILURE")),
                        "task_risk":profile.risk,"task_scope":profile.scope,"input_tokens":result.usage.get("input_tokens"),"output_tokens":result.usage.get("output_tokens"),
                        "total_tokens":result.usage.get("total_tokens"),"reported_cost":result.usage.get("reported_cost"),"estimated_cost":result.usage.get("estimated_cost"),
                        "ponytail_enabled":result.usage.get("ponytail_enabled"),"caveman_enabled":result.usage.get("caveman_enabled"),"policy_source":result.usage.get("policy_source"),
                        "escalation_level":result.usage.get("escalation_level"),"escalation_reason":result.usage.get("escalation_reason")})
                result.usage["execution_id"]=eid
            return result
        result=execute(route,attempt)
        provider_failure=(result.error or "").startswith("PROVIDER_FAILURE") or (result.error is None and result.exit_code not in {None,0})
        if not result.success and fallback and provider_failure:
            second = self.router.route(
                role, exclude=route_excludes | {route.provider},
                author_provider=author_provider, task=task,
                author_models=auth_models_list, author_role=author_role, numeric_sensitive=is_numeric
            )
            if second.provider == "unavailable":
                if "INSUFFICIENT_INDEPENDENT_PROVIDERS" in getattr(second, "reason", ""):
                    result.error = "INSUFFICIENT_INDEPENDENT_PROVIDERS"
                    return result
            if self.cost_router and second.provider!="unavailable":
                second_decision=self.cost_router.assess(role,second,task,author_provider,(),override_model=None)
                second=second_decision["actual_route"]
                decision=second_decision
            fallback_error=cost_safety_error(second,decision)
            if fallback_error: return AgentResult(second.provider,second.model,role,False,error=fallback_error)
            if second.provider != "unavailable":
                if self.on_fallback and not self.on_fallback(role,second.provider,second.model):
                    result.error="PROVIDER_FAILURE: interactive fallback aborted"
                    return result
                fallback_res = execute(second, attempt)
                fallback_res.fallback_reason = f"cross_provider_fallback_from_{route.provider}"
                fallback_res.usage["fallback_reason"] = fallback_res.fallback_reason
                result = fallback_res
        if self.active_stage_role == role:
            self.active_stage_name = None
            self.active_stage_role = None
            self.active_stage_artifacts = []
        return result
